Algoritmo "operadores"

Var
   A, B, C, D, F, G: Real

Inicio
      // Valor Absoluto
      A <- Abs(-50)
      Escreval(A)
      
      // Exponenciação
      B <- Exp(9, 5)
      Escreval(B)
      
      // Raiz Quadrada
      C <- RaizQ(81)
      Escreval(C)
      
      // Parte inteira
      D <- Int(RaizQ(90))
      Escreval(D)
      
      // Grau para Radiano
      F <- GraupRad(90)
      Escreval(F)
      
      // Seno
      G <- Sen(GraupRad(90))
      Escreval(G)


Fimalgoritmo